- name: data types 
  hosts: local
  connection: yes #for localhost
  vars:
   course: devops
   duration: 5 years
   company: L@T
  topics: #list
  - linux
  - ansible
  - teraform
  - shell

  tools: #map / distionary
   ci: jenkin
   cm: ansible
   cloud: aws

  live: true
  tasks:
  - name: print the course information
    ansible.builtin.debug:
     msg: "I am learning {{ course }}, with duration {{ duration }}, company {{ company }} , topics are {{ topics }},tools is {{ tools }},live {{ live }}, "

