- name: install package
  hosts: web
  become: yes
  tasks:
   - name:
     ansible.builtin.package:
       name: "{{ item }}"
       state: present
     loop:
     - mysql
     - nginx
     - postfix
     - httpd
         
      