- name: nginx install
  hosts: web
  become: yes
  tasks:
   - name: nginx
     ansible.builtin.package:
      name: nginx
      state: present

   - name: nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes  
