- name: nginx install and run
  hosts: web
  become: yes #take sudo access
  tasks:
   - name: install nginx
     ansible.builtin.package:
       name: ngnix
       state: present

    - name: run nginx
      ansible.builtin.service:
       name: ngnix
       state: started
       enabled: yes
