- name: variable with prompt
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: enter the course name
      private: false # not confidential
    - name: DURATION 
      prompt: enter duration
      private: false # not confidential
    - name: COMPANY
      prompt: enter company name
      private: false # not confidential
  tasks:
   - name: 
     ansible.builtin.debug:
       msg: "I am working with {{COURSE}}, Duration is {{DURATION}} and company name is {{COMPANY}}"

